name: Enriched Beans Release Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven
        uses: stCarolas/setup-maven@master

      - name: Run a one-line script
        run: mvn clean install
