name: Enriched Beans Release Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Maven
        uses: stCarolas/setup-maven@master
        with:
          maven-version: 3.8.4

      - name: Run a one-line script
        run: mvn --version
